#Build stage
FROM registry.access.redhat.com/ubi9/ubi AS build-env
LABEL maintainer="gedasilv@redhat.com"
LABEL description="SCM Gitea unsupported image"

ARG GOPROXY
ENV GOPROXY ${GOPROXY:-direct}

ARG GITEA_VERSION
ARG TAGS="sqlite sqlite_unlock_notify"
ENV TAGS "bindata timetzdata $TAGS"
ARG CGO_EXTRA_CFLAGS

#Build deps
RUN yum install -y git nodejs npm make go

#Clone repository
RUN git clone https://github.com/go-gitea/gitea.git

WORKDIR /gitea

RUN make clean-all build

# Begin env-to-ini build
RUN go build ./contrib/environment-to-ini/environment-to-ini.go

FROM registry.access.redhat.com/ubi9/ubi
LABEL maintainer="gedasilv@redhat.com"
LABEL description="SCM Gitea unsupported image"

EXPOSE 2222 3000

RUN yum install -y \
    bash \
    ca-certificates \
    gettext \
    git \
    openssh \
    sqlite \
    gnupg

RUN groupadd  git
RUN adduser -d /data/git -s /bin/bash -u 1000 -g git git
  
RUN mkdir -p /var/lib/gitea /etc/gitea
RUN chown git:git /var/lib/gitea /etc/gitea

#ENV USER git
#ENV GITEA_CUSTOM /data/gitea

#VOLUME ["/data"]

#ENTRYPOINT ["/usr/bin/entrypoint"]
#CMD ["/bin/s6-svscan", "/etc/s6"]


COPY --from=build-env /gitea/docker/rootless /
COPY --from=build-env /gitea/gitea /app/gitea/gitea
COPY --from=build-env /gitea/environment-to-ini /usr/local/bin/environment-to-ini
#COPY --from=build-env /gitea/docker/root/usr/bin/entrypoint /usr/bin/entrypoint
#RUN chmod 755 /usr/bin/entrypoint /app/gitea/gitea /usr/local/bin/gitea /usr/local/bin/environment-to-ini
RUN chmod 755 /usr/local/bin/docker-entrypoint.sh /usr/local/bin/docker-setup.sh /app/gitea/gitea /usr/local/bin/gitea /usr/local/bin/environment-to-ini

#git:git
USER 1000:1000
ENV GITEA_WORK_DIR /var/lib/gitea
ENV GITEA_CUSTOM /var/lib/gitea/custom
ENV GITEA_TEMP /tmp/gitea
ENV TMPDIR /tmp/gitea

#TODO add to docs the ability to define the ini to load (useful to test and revert a config)
ENV GITEA_APP_INI /etc/gitea/app.ini
ENV HOME "/var/lib/gitea/git"
VOLUME ["/var/lib/gitea", "/etc/gitea"]
WORKDIR /var/lib/gitea

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD []
